# Makefile for Pinocchio

all:
	cd asf && $(MAKE)
	cd Pinocchio && $(MAKE)
	cd DemoUI && $(MAKE)

depend:
	cd asf && $(MAKE) depend
	cd Pinocchio && $(MAKE) depend
	cd DemoUI && $(MAKE) depend

clean:
	cd asf && $(MAKE) clean
	cd Pinocchio && $(MAKE) clean
	cd DemoUI && $(MAKE) clean


# DO NOT DELETE
